In [2]:
from manim import *
import pandas as pd
import numpy as np


config.media_width = "75%"
config.verbosity = "WARNING"

Manim Community v0.17.3

## Load The Dataset to Display

In [3]:
from pathlib import Path

file_name = Path('puppy_weights.csv')
root_folder = Path('data')

file_path = root_folder / file_name

In [4]:
csv_df = pd.read_csv(file_path).set_index('Date')

In [5]:
csv_df

,Emma,Simba,Ragnar,Luna,Rolo,Big Black,Jucumari,Tiny,Black1,Black2
Date,,,,,,,,,,
2019-03-12,28000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-03-14,28000.0,364.0,439.0,310.0,0.0,414.0,343.0,272.0,378.0,377.0
2019-03-16,28000.0,477.0,545.0,383.0,0.0,519.0,410.0,350.0,499.0,496.0
2019-03-18,28000.0,590.0,658.0,473.0,0.0,609.0,518.0,405.0,607.0,606.0
2019-03-19,28000.0,666.0,718.0,504.0,0.0,668.0,562.0,460.0,704.0,698.0
...,...,...,...,...,...,...,...,...,...,...
2020-07-13,32910.0,35660.0,28930.0,33980.0,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-16,32870.0,35330.0,29420.0,33060.0,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-19,32770.0,35690.0,29290.0,33400.0,NaN,NaN,NaN,NaN,NaN,NaN
2020-07-21,33140.0,36000.0,29250.0,33580.0,NaN,NaN,NaN,NaN,NaN,NaN

### Fill-In Gaps in the Data
If we take a look at the dataset, we can see that several of the dogs do not have any data past a certain date (they were adopted). I thought that a simple fix for this would be to simply extend the last value of those puppies for all the following rows.

In cases where there are missing values in between datapoints, I will fill it with the average of the surrounding values.

## Load Images

## Static Bar Chart

In [ ]:
%%manim -qm StaticBarChart

class StaticBarChart(Scene):
    def construct(self):